version: 2
updates:
- package-ecosystem: elm
  cooldown:
    default-days: 10
  directories:
    - "/"
    - "/review"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  cooldown:
    default-days: 10
  directories:
    - "/.github"
    - "/.github/workflows"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Sydney
  open-pull-requests-limit: 10
- package-ecosystem: nix
  cooldown:
      default-days: 10
  directory: "/"
  schedule:
      interval: daily
      time: "08:00"
      timezone: Australia/Sydney
  open-pull-requests-limit: 10
