# This file was generated by `elm2nix init > default.nix`
#
# the default output of `elm2nix init` doesn't seem to work with Flakes; I've
# manually replaced the next two lines:
# { nixpkgs ? <nixpkgs>, config ? { } }:
# with (import nixpkgs config);
{ pkgs, minimalElmSrc }:
with pkgs;

let
  mkDerivation = { srcs ? ./elm-srcs.nix, src, name, srcdir ? "./src"
    , targets ? [ ], registryDat ? ./registry.dat, outputJavaScript ? false }:
    stdenv.mkDerivation {
      inherit name src;

      buildInputs = (with pkgs.elmPackages; [ elm elm-json elm-test ])
        ++ lib.optional outputJavaScript nodePackages.uglify-js;

      buildPhase = pkgs.elmPackages.fetchElmDeps {
        elmPackages = import srcs;
        elmVersion = "0.19.1";
        inherit registryDat;
      };

      # checkPhase manually added; not part of `elm2nix init`.
      doCheck = true;
      checkPhase = ''
        ELM_JSON_VERSION="$(elm-json --version | cut -d ' ' -f 2)"
        echo "elm-json is present, at version: $ELM_JSON_VERSION"
        mkdir -p "$ELM_HOME/elm-tooling/elm-json/$ELM_JSON_VERSION"
        ln -s ${pkgs.elmPackages.elm-json}/bin/elm-json \
          "$ELM_HOME/elm-tooling/elm-json/$ELM_JSON_VERSION/elm-json"
        elm-test
      '';

      installPhase = let
        elmfile = module:
          "${srcdir}/${builtins.replaceStrings [ "." ] [ "/" ] module}.elm";
        extension = if outputJavaScript then "js" else "html";
      in ''
        mkdir -p $out/share/doc
        ${lib.concatStrings (map (module: ''
          echo "compiling ${elmfile module}"
          elm make ${
            elmfile module
          } --output $out/${module}.${extension} --docs $out/share/doc/${module}.json
          ${lib.optionalString outputJavaScript ''
            echo "minifying ${elmfile module}"
            uglifyjs $out/${module}.${extension} --compress 'pure_funcs="F2,F3,F4,F5,F6,F7,F8,F9,A2,A3,A4,A5,A6,A7,A8,A9",pure_getters,keep_fargs=false,unsafe_comps,unsafe' \
                | uglifyjs --mangle --output $out/${module}.min.${extension}
          ''}
        '') targets)}
      '';
    };
in mkDerivation {
  name = "tulars-elm2nix-0.1.0";
  srcs = ./elm-srcs.nix;
  src = minimalElmSrc;
  targets = [ "Main" ];
  srcdir = "./app";
  outputJavaScript = true;
}
