#!/usr/bin/env bash

set -e

if [ -d .git ]; then
  GIT_HASH="$(git rev-parse HEAD)";
else
  GIT_HASH="NO_GIT_REPO";
fi;

echo "$GIT_HASH" > dist/version.txt

cat >./dist/context.js <<EOF
// This file generated by ../write-context-js.sh

window.appContext = {
    gitHash: '${GIT_HASH}',
}
EOF
