name: "Build with Nix & Cachix"
on:
    pull_request:
    push:
jobs:
    tests:
        runs-on: ubuntu-latest
        environment: someEnviro
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@v24
              with:
                  nix_path: nixpkgs=channel:nixos-unstable
            - uses: cachix/cachix-action@v13
              with:
                  name: r-k-b
                  # If you chose signing key for write access
                  #signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
                  # If you chose API tokens for write access OR if you have a private cache
                  authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
            - name: Keep the Flake up-to-date and healthy
              uses: DeterminateSystems/flake-checker-action@v5
              with:
                  fail-mode: true
            - run: nix flake check
            - run: nix build .
            - run: nix shell --command echo "Computer says OK."
