name: "Build with Nix"
on:
    pull_request:
    push:
jobs:
    tests:
        runs-on: ubuntu-latest
        environment: someEnviro
        steps:
            - uses: actions/checkout@v4
            - uses: cachix/install-nix-action@V27
              with:
                  nix_path: nixpkgs=channel:nixos-unstable
            - uses: DeterminateSystems/magic-nix-cache-action@v7
            - name: Keep the Flake up-to-date and healthy
              uses: DeterminateSystems/flake-checker-action@v8
              with:
                  fail-mode: true
            - run: nix flake check
            - run: nix build .
